@baseUrl = http://localhost:3000/api/v1

# Books
### Get book by ISBN
GET {{baseUrl}}/books/isbn/9780141182636

### Get books by title
GET {{baseUrl}}/books/search?q=harry+potter&page=1

# Users
### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "email@example.com",
  "password": "securepassword"
}

### me
GET {{baseUrl}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmExYzE0YS1iYTFlLTRhY2QtOGNiYS1mODNkYmJhZTdiODYiLCJlbWFpbCI6ImVtYWlsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUyMTc1OTczLCJleHAiOjE3NTIxNzk1NzMsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.jJ8djRun0bIC1hGZp4vRF8CkOxF9A4jz0rOBTeOPaAM

# Auth
### Login user
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "securepassword"
}

